### ISSUE TITLE
Modifed Newton Method Cannot converge

### ISSUE THREAD

**Issue by fz920** [BrianChung10/SOP#2]
Hi John, about GOAL 4 in the pdf you send to us, I have computed the Jacobian for F[u] which is indeed not invertible since the first and last columns and rows are zeros. To make it invertible, I think we should place 1 in the Jacobian[1, 1] and Jacobian[end, end] so that the Jacobian is invertible while preserving the boundary conditions (since the 1’s do not change the first and last entries of our initial guess). But the problem is after implementing the modified Newton method, I cannot get a convergent solution for the ODE. Could you have a look at the code and see where the problem is? The codes are in the simple_deflation / finite_difference.jl
 
Thanks in advance!

**Comment by ioannisPApapadopoulos** [comment]
Actually to me it looks like it's working, your tolerance `eps=1e-13` is just too tight. The norm of `F(x1)` seems to stagnate around 1e-12 (probably due to ill-conditioning of A). 

**Major point**. Do not do `x=x-inv(A)*f(x)`, but rather `x=x-(A\f(x))`. `Inv(A)` actually computes the inverse matrix and this is slow and prone to numerical instability. `A\f(x)` instead uses much faster tricks to get a numerical stable result.

**Comment by fz920** [comment]
> 

I see. Thanks for pointing that out!
