### ISSUE TITLE
Problems about solving the Bratu equation

### ISSUE THREAD

**Issue by fz920** [BrianChung10/SOP#5]
Hi, I am trying to plot the bifurcation diagram of the Bratu equation, but I get the SingularException Error for some values of lambda and now I get the MethodError: no method matching (::var"#F#17"{Float64})(::typeof(F)). The codes are in the Finite_Difference_1D / Goal_3_5.jl

Could you help with this? Thanks!

**Comment by fz920** [comment]
MethodError: no method matching (::var"#F#17"{Float64})(::typeof(F))
Closest candidates are:
  (::var"#F#17")(::AbstractVector{T}) where T at ~/Desktop/group_project_deflation/SOP/Finite_Differences_1D/Goal_3-5.jl:89
Stacktrace:
 [1] newton(f::var"#F#17"{Float64}, x0::Function, max_iter::Int64, eps::Float64)
   @ Main ~/Desktop/group_project_deflation/SOP/Finite_Differences_1D/Goal_3-5.jl:35
 [2] newton(f::Function, x0::Function)
   @ Main ~/Desktop/group_project_deflation/SOP/Finite_Differences_1D/Goal_3-5.jl:33
 [3] bratu_solve(lambda::Float64, x0::Function)
   @ Main ~/Desktop/group_project_deflation/SOP/Finite_Differences_1D/Goal_3-5.jl:98
 [4] top-level scope
   @ ~/Desktop/group_project_deflation/SOP/Finite_Differences_1D/Goal_3-5.jl:107

**Comment by ioannisPApapadopoulos** [comment]
I get an error earlier at line 59 in that script. Can you fix that first and then I can see?

By the way, tag me like @fz920 when making issues otherwise I do not get a notification. 

```
ERROR: MethodError: objects of type Int64 are not callable
Stacktrace:
 [1] (::var"#9#10"{Vector{Float64}, typeof(F)})(x::Vector{Float64})
   @ Main c:\Users\john.papad\.julia\dev\SOP\Finite_Differences_1D\Goal_3-5.jl:51
 [2] newton(f::var"#9#10"{Vector{Float64}, typeof(F)}, x0::Vector{Float64}, max_iter::Int64, eps::Float64)
   @ Main c:\Users\john.papad\.julia\dev\SOP\Finite_Differences_1D\Goal_3-5.jl:35
 [3] newton
   @ c:\Users\john.papad\.julia\dev\SOP\Finite_Differences_1D\Goal_3-5.jl:33 [inlined]
 [4] deflated_newton(x0::Vector{Float64}, x1::Vector{Float64}, f::typeof(F))
   @ Main c:\Users\john.papad\.julia\dev\SOP\Finite_Differences_1D\Goal_3-5.jl:52
 [5] top-level scope
   @ c:\Users\john.papad\.julia\dev\SOP\Finite_Differences_1D\Goal_3-5.jl:59
```

**Comment by ioannisPApapadopoulos** [comment]
Ignore my previous comment if you saw it. Tag me in issues like @fz920 otherwise I do not receive a notification. You have an error on line 104 `n=length(lambda)` but `lambda` is not defined. Just looking at the code you have `sol = bratu_solve(lambda, F)` in line 108 but have have the definition as `function bratu_solve(lambda, x0)` in line 87, i.e. you give it `x0` in your definition but give it `F` in your call.

**Comment by fz920** [comment]
@ioannisPApapadopoulos Thanks for pointing that out. I have fixed that error. But I found that for some particular values of lambda, I get different errors. For example, in the Finite_Difference_1D / Goal3_6.jl, when lambda = 1.1 I get the SingularException Error ,and when lambda = 2, I get the StackOverflow Error. Could you explain a bit about these errors? When ploting the bifurcation diagram, should we just ignore these values of lambda that cause the errors? Thanks in advance!

**Comment by ioannisPApapadopoulos** [comment]
`SingularExceptionError` means that the matrix you are inverting is numerically singular, i.e. not invertible. This is a nonlinear problem, so given some iterate x^k, you can imagine that the induced Jacobian could be singular in some circumstances, Newton is not perfect. You can try damping the Newton iteration (multiple the update with a constant <1) and see if that works. 

However when I ran the code for lambda=1.1, I did not get an error at all, it worked? 

Your `StackOverflowError` seems to come from the fact that `deflated_newton` command does not converge when lambda=2. Maybe try and damp that one? 

If you cannot get values to work that's fine, just skip them. But ideally have enough values so that the bifurcation curve looks smooth.

**Comment by dlfivefifty** [comment]
If you do ` qr(A) \b ` it will do a least squares fit instead of trying to inverse… may be more robust

**Comment by fz920** [comment]
Thank you for your suggestions. I have created a bifurcation diagram but the lines in the diagram are not smooth enough. I think some values in the `sol` caused this problem. Do you know how to improve this diagram? Thanks!
<img width="729" alt="Screen Shot 2022-06-02 at 17 22 03" src="https://user-images.githubusercontent.com/97394947/171677603-3e80027e-ab8d-40ef-a057-6edfadb2545e.png">

**Comment by ioannisPApapadopoulos** [comment]
Newton is a not globally convergent. Given a random initial guess, you're not guaranteed to converge to anything. If you want to make it global, then you also add a linesearch, i.e. an algorithm that adaptively damps the Newton update. Have you tried damping the Newton update with just a constant factor like 0.1?

**Comment by GianfrancoVieri** [comment]
yeah sorry, I asked in the wrong section, this should be under the painleve equation instead of the bratu equation

**Comment by ioannisPApapadopoulos** [comment]
This still applies to the disconnected bifurcation diagram you have. You also have a free choice of initial guess. Instead of just choosing a zero initial guess every time, then you could the solutions and the previous value of lambda as the guess for the next value of lambda. Much more likely to converge

**Comment by dlfivefifty** [comment]
This is called homotopy (where you vary a parameter and use the previous solution as an initial guess to the new problem).

@ioannisPApapadopoulos : is there a simple example of a discontinuous bifurcation example?

**Comment by GianfrancoVieri** [comment]
Oh I see, thank you so much! @ioannisPApapadopoulos  @dlfivefifty , I'll try to reconfigure the code to adapt to the value of the last lambda.
